/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shivani
 */

import java.sql.*;
import java.sql.PreparedStatement;
import javax.swing.*;
import java.lang.*;
public class Bill extends javax.swing.JFrame {
    
    Connection conn=null;
    PreparedStatement stmt=null;
    /**
     * Creates new form Bill
     */
    public Bill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        gen_bill = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cuid = new javax.swing.JTextField();
        subLa = new javax.swing.JLabel();
        subLat = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        paym = new javax.swing.JTextField();
        disL = new javax.swing.JLabel();
        discLt = new javax.swing.JLabel();
        taxL = new javax.swing.JLabel();
        taxLt = new javax.swing.JLabel();
        grtotL = new javax.swing.JLabel();
        grtott = new javax.swing.JLabel();
        pro = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 237, 237));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Thank you for choosing Ivory Bloom Resorts");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );

        gen_bill.setBackground(new java.awt.Color(255, 255, 255));
        gen_bill.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        gen_bill.setText("Click to generate Bill");
        gen_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gen_billActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel1.setText("Enter Customer id");

        cuid.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N

        subLa.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 15)); // NOI18N

        subLat.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 15)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel3.setText("Payment Mode");

        paym.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N

        disL.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 15)); // NOI18N

        discLt.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 15)); // NOI18N

        taxL.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 15)); // NOI18N

        taxLt.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 15)); // NOI18N

        grtotL.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N

        grtott.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N

        pro.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        pro.setText("Proceed to checkout");
        pro.setEnabled(false);
        pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(grtotL, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(grtott, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(cuid, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subLa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taxL, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(disL, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(discLt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(taxLt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subLat, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paym, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(gen_bill)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pro, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuid, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(paym, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gen_bill, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(subLa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(disL, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(subLat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(discLt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(taxL, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(taxLt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grtotL, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grtott, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(pro)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gen_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gen_billActionPerformed
        // TODO add your handling code here:
        pro.setEnabled(true);
        String cid=cuid.getText();
        ResultSet rs=null;
        try{
           Connection conn = null;
        try{
            conn=MyConnection.getConnection();
        }catch(Exception ex)
        {
            System.out.println(ex.getMessage());
        }
        double subtotal=0;
        String rid="";
        stmt=conn.prepareStatement("Select cost,days,reservation_id from room where c_id=?");
        stmt.setString(1,cid);
        rs=stmt.executeQuery();
        //
        String c1="",d1="";
          while(rs.next())
          {
               rid=rs.getString("reservation_id");
               c1=rs.getString("cost");
               d1=rs.getString("days");
          }
          double a=Double.parseDouble(c1);
          int b=Integer.parseInt(d1);
          subtotal=a*b;
          System.out.println("Room Cost: "+subtotal);
          stmt=conn.prepareStatement("Select tf_cost from eats where cust_id=?");
          stmt.setString(1,cid);
          rs=stmt.executeQuery();
          double i=0;
          while(rs.next())
          {
              i=Double.parseDouble(rs.getString("tf_Cost"));
          }
          subtotal=subtotal+i;
          
         stmt=conn.prepareStatement("Select acti_cost from enrolls where cust_id=?");
          stmt.setString(1,cid);
          rs=stmt.executeQuery();
           while(rs.next())
          {
              i=Double.parseDouble(rs.getString("acti_cost"));
          }
          subtotal=subtotal+i;
          
          
          stmt=conn.prepareStatement("Select spa_cost from uses where cust_id=?");
          stmt.setString(1,cid);
          rs=stmt.executeQuery();
           while(rs.next())
          {
              i=Double.parseDouble(rs.getString("spa_cost"));
          }
          subtotal=subtotal+i;
          double tax=((double)17/100)*subtotal;
          System.out.println(tax);
          double disc=((double)10/100)*subtotal;
          subLa.setText("Subtotal: ");
          subLat.setText("Rs ."+String.valueOf(subtotal));
          System.out.println("Subtotal: "+subtotal);
          disL.setText("Discount Obtained (10%): ");
          discLt.setText("Rs ."+String.valueOf(disc));
          taxL.setText("Tax (17%): ");
          taxLt.setText("Rs. "+String.valueOf(tax));
          double grt=subtotal+tax-disc;
          grtotL.setText("Grand Total: ");
          grtott.setText("Rs. "+String.valueOf(grt));
          
          
          System.out.println(rid);
           String query="INSERT into bill values(?,?,?,?,?,?,?)";
           
           stmt=conn.prepareStatement(query);
           stmt.setString(1,rid);
           stmt.setString(2,paym.getText());
           stmt.setString(3,String.valueOf(subtotal));
           stmt.setString(4,String.valueOf(tax));
           stmt.setString(5,String.valueOf(disc));
           stmt.setString(6,String.valueOf(grt));
           stmt.setString(7,cid);
           stmt.executeUpdate();
 
       
        }catch(Exception e)
        {
             JOptionPane.showMessageDialog(null,e);
             pro.setEnabled(false);
        }
    }//GEN-LAST:event_gen_billActionPerformed

    private void proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proActionPerformed
        // TODO add your handling code here:
         ResultSet rs=null;
        try{
           Connection conn = null;
        try{
            conn=MyConnection.getConnection();
        }catch(Exception ex)
        {
            System.out.println(ex.getMessage());
        }
        String cid=cuid.getText();
         stmt=conn.prepareStatement("delete from eats where cust_id=?");
          stmt.setString(1,cid);
          stmt.executeUpdate();
           stmt=conn.prepareStatement("delete from uses where cust_id=?");
          stmt.setString(1,cid);
          stmt.executeUpdate();
          stmt=conn.prepareStatement("delete from enrolls where cust_id=?");
          stmt.setString(1,cid);
          stmt.executeUpdate();
          stmt=conn.prepareStatement("delete from room where c_id=?");
          stmt.setString(1,cid);
          stmt.executeUpdate();
        JOptionPane.showMessageDialog(null, "Successfully Checked Out");
        dispose();
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null,e);
            
        }
        
        
    }//GEN-LAST:event_proActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Welcome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cuid;
    private javax.swing.JLabel disL;
    private javax.swing.JLabel discLt;
    private javax.swing.JButton gen_bill;
    private javax.swing.JLabel grtotL;
    private javax.swing.JLabel grtott;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField paym;
    private javax.swing.JButton pro;
    private javax.swing.JLabel subLa;
    private javax.swing.JLabel subLat;
    private javax.swing.JLabel taxL;
    private javax.swing.JLabel taxLt;
    // End of variables declaration//GEN-END:variables
}
